server:
  port: 9002
spring:
  cloud:
    stream:
      # 如果你项目里只对接一个中间件，那么不用定义binders
      # 当系统要定义多个不同消息中间件的时候，使用binders定义
      binders:
        my-rabbit:
          type: rabbit # 消息中间件类型
          environment: # 连接信息
            spring:
              rabbitmq:
                host: 192.168.3.159
                port: 5672
                username: admin
                password: admin
      bindings:
        # 添加coupon - Producer
        onceEvidenceEnd-out-0:
          destination: once-evidence-topic
          content-type: application/json
          binder: my-rabbit
        onceEvidenceEnd-in-0:
          destination: once-evidence-topic
          content-type: application/json
          # 消费组，同一个组内只能被消费一次
          group: billing-group
          binder: my-rabbit
          consumer:
            # 如果最大尝试次数为1，即不重试
            # 默认是做3次尝试
            max-attempts: 1
            # 两次重试之间的初始间隔
            backOffInitialInterval: 2000
            # 重试最大间隔
            backOffMaxInterval: 10000
            # 每次重试后，间隔时间乘以的系数
            backOffMultiplier: 2
            # 如果某个异常你不想重试，写在这里
#            retryableExceptions:
#              java.lang.IllegalArgumentException: false


