server:
  port: 9000
spring:
  aop:
    proxy-target-class: true
    auto: true
  application:
    name: filoink


  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.3.159:3306/libi_zeus?useUnicode=true&characterEncoding=utf8&verifyServerCertificate=false&useSSL=false&useOldAliasMetadataBehavior=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
    username: root
    password: 123456
    druid:
      url: jdbc:mysql://192.168.3.159:3306/libi_zeus?useUnicode=true&characterEncoding=utf8&verifyServerCertificate=false&useSSL=false&useOldAliasMetadataBehavior=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
      username: root
      password: 123456
      initial-size: 10
      #最大
      max-active: 100
      #最小
      min-idle: 10
      #最大等待连接时间
      max-wait: 60000
      #打开PSCache,并且指定每个连接PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      #配置间隔多久才进行一次检测,检测需要关闭的空闲连接,单位是毫秒
      time-between-eviction-runs-millis: 60000
      #配置一个连接在池中最小生存的时间,单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
#      #配置监控统计拦截的filters,去掉后监控界面sql将无法统计,'wall'用于防火墙
#      filters: stat, wall, log4j
      filter:
        stat:
          #缺省值为3秒 此处修改为10秒
          slow-sql-millis: 10000
          #日志记录
          log-slow-sql: true

      #是否合并多个dataSource的监控数据
      use-global-data-source-stat: true

      #连接进行保活处理
      keep-alive: true
      #关闭长时间不用的连接
      remove-abandoned: true
      #长时间不用的连接的超时时间 单位毫秒
      remove-abandoned-timeout-millis: 30000
      #输出日志
      log-abandoned: true

mybatis-plus:
  mapper-locations: classpath*:sqlmap/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: org.libi.user.impl.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #逻辑删除配置
    logic-delete-value: 1
    logic-not-delete-value: 0
    #自定义SQL注入器
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 每次查询结束都会清掉一级缓存 session:在同一个 sqlSession 内，对同样的查询将不再查询数据库，直接从缓存中获取
    local-cache-scope: statement